### ISSUE TITLE
Redis 7

### ISSUE THREAD

**Issue by anludke** [sclorg/redis-container#124]
Hi there,

Is there a plan and timeline to publish Redis 7 in Red Hat Container Images Catalog?

Thank you.

**Comment by phracek** [comment]
This should be covered by PR https://github.com/sclorg/redis-container/pull/146

**Comment by pkubatrh** [comment]
Note that what Petr linked above will only cover c9s version of the image which will then be shipped to quay.io. Red Hat Container Images Catalog will get the image in some future version of RHEL9.

**Comment by AlexStorm1313** [comment]
Currently the README links to a fedora redis-7 image on quay.io, but the image is non existent at the moment. Is this an oversight?

**Comment by zmiklank** [comment]
> Currently the README links to a fedora redis-7 image on quay.io, but the image is non existent at the moment. Is this an oversight?

The image you mentioned exists in quay.io and I can access it just right. However it has different access settings than other our images - the repository seems to be set as private.. That could be the reason you can not access it.

@phracek is there any reason for quay.io/fedora/redis-7 being private repository?

**Comment by phracek** [comment]
it was typo.

**Comment by zmiklank** [comment]
I've set the repo to public. The image should be accesible for everyone now. Thanks @AlexStorm1313 for notifying us.

**Comment by AlexStorm1313** [comment]
Thank you! @zmiklank

**Comment by phracek** [comment]
@AlexStorm1313 redis-7 is available on quay.io. @anludke Does it make sense to close this issue in case it is already available on quay.io based on fedora base image?

Currently we do not have any timeline, when the image will be available in Red Hat Container catalog.

**Comment by phracek** [comment]
@AlexStorm1313 @anludke . redis-7 is now available in Red Hat Container catalog. Can we close this issues?

**Comment by AlexStorm1313** [comment]
Excuse me for the late reply @phracek, setting the quay.io repo to public solves it for me.
