### ISSUE TITLE
RFE - control bind address with environment variable

### ISSUE THREAD

**Issue by yrro** [sclorg/redis-container#128]
I'm deploying software into OpenShift and would like to use this image as a sidecar container to run alongside my application.

I'd like to request an environment variable that I can set to cause redis to listen only on `127.0.0.1` instead of `0.0.0.0`.

Current workaround is to rebuild the container image with this `Dockerfile`:

```
FROM registry.redhat.io/rhel8/redis-6:latest

USER 0

RUN echo $'log_info "Configuring redis to listen on localhost only ..."\necho "bind 127.0.0.1" >> "${REDIS_CONF}"\n' > /usr/share/container-scripts/redis/post-init.sh

USER 1001
```

**Comment by phracek** [comment]
This issue is fixed by #153
