### ISSUE TITLE
evolve this repo

### ISSUE THREAD

**Issue by goern** [sclorg/redis-container#14]
heya, do you think this repo can evolve into something that is close to https://github.com/openshift/origin/tree/master/examples/statefulsets/redis ? :)

**Comment by phracek** [comment]
@goern The link, you provided, did not exist. What do you want to evolve? Can you please be more specific?

**Comment by phracek** [comment]
@goern Closing this issue. It seems, like it is not relevant for this repo. We need more details. Feel free to re-open it.
