### ISSUE TITLE
Discontinuation of redis-7 for CentOS 9

### ISSUE THREAD

**Issue by mfocko** [sclorg/redis-container#166]
We've discovered[^1] two weeks ago that you've discontinued that redis-7 image for CentOS 9.

First of all, going through the quay.io repositories and having a reasonably obnoxious experience finding this repo (which is pretty much standard UX across Quay and Docker Hub), I understand that it's hard to propagate such decisions[^2] to the users, though I would very much appreciate if you tried to employ some way to deprecate images and warn potentially affected users (maybe warnings in the entrypoints of the images, even ASCII art to catch the eye; I definitely would've noticed that as I check on the deployment here-and-there).

My issue with this comes from the fact that I was not in any way aware of the discontinuation and “pulling the plug” on it. There are no commits, there are no issues, there are no warnings. I've found out about this decision at 5:30PM when the production died ( funnily enough, before the staging deployment :) ).

We already have [plans](https://github.com/packit/deployment/issues/561) to move on and since there are multiple alternatives, are you planning to maintain image of at least one of the forks, or we should look around for alternatives (possibly even non-CentOS based)?

Thanks.

[^1]: sadly on our production deployment…
[^2]: like discontinuation of the maintenance because of the license changes

**Comment by phracek** [comment]
The redis-7-c9s container is updated again. It looks like schedule rebuild disables also build-and-push action. Feel free to use it again. See https://quay.io/repository/sclorg/redis-7-c9s?tab=tags

**Comment by pkubatrh** [comment]
Closing as the immediate issue has been fixed.
