### ISSUE TITLE
Allow users to change configuration easily

### ISSUE THREAD

**Issue by hhorak** [sclorg/redis-container#2]
We should have an easy way to change configuration of the server easily. If we use `post-init` file for that, we should at least document how to do it properly.

**Comment by luciddreamz** [comment]
Feels like we could re-use something close to the logic from MongoDB here? https://github.com/sclorg/mongodb-container/blob/master/3.2/root/usr/bin/run-mongod#L29-L41

**Comment by hhorak** [comment]
Yes, I'd like to use something like that.

**Comment by MPParsley** [comment]
Could we add something like this to https://github.com/sclorg/redis-container/blob/master/3.2/root/usr/bin/run-redis:

`echo -e "\ninclude /redis-master/redis.conf" >> /etc/redis.conf
`

See https://github.com/kubernetes/website/issues/30376

**Comment by phracek** [comment]
Closing this issue, Feel free to reopen it if it is still valid. Thank you.
