### ISSUE TITLE
Please upgrade to redis 5.0.8 to close security issues

### ISSUE THREAD

**Issue by strouja** [sclorg/redis-container#59]
I just sent an email to secalert@redhat.com as well

Can you please update your redis 5 UBI 8 container to redis 5.0.8?  We are now back-level since we were forced to move to UBI for "security improvement reasons"  
We want to move to 5.0.8 but can't as we are forced to stay on UBI images which are not up to date.  

Here is the download
http://download.redis.io/releases/redis-5.0.8.tar.gz

Here are the release notes with security fixes
https://raw.githubusercontent.com/antirez/redis/5.0/00-RELEASENOTES

See here
https://hub.docker.com/_/redis/

FYI I downloaded last night your redis 5 image from here and verified it is running the old, outdated and insecure version despite being published 7 days ago
https://access.redhat.com/containers/?tab=tech-details#/registry.access.redhat.com/rhel8/redis-5

Here is evidence in case you need it

```
PS C:\Users\strou> docker images
REPOSITORY                         TAG                   IMAGE ID            CREATED             SIZE
PS C:\Users\strou> docker images
REPOSITORY                         TAG                   IMAGE ID            CREATED             SIZE

registry.redhat.io/rhel8/redis-5   latest                02c2c056796b        2 weeks ago         307MB

PS C:\Users\strou> docker run -it registry.redhat.io/rhel8/redis-5 /bin/bash
bash-4.4$ redis-server -v
Redis server v=5.0.3 sha=00000000:0 malloc=jemalloc-5.1.0 bits=64 build=46fe5c58c7e94a15

```

**Comment by notroj** [comment]
Can you please file this in a support ticket?  This issue tracker is for issues specific to the container scripts.
