### ISSUE TITLE
Publish centos-images on quay.io

### ISSUE THREAD

**Issue by ibotty** [sclorg/redis-container#69]
It would be great to get the images from quay.io instead of docker.io because of recent rate limits.

**Comment by phracek** [comment]
It is planned to move it soon. I am planning to do it this week. Please be pationed.

**Comment by ibotty** [comment]
Thank you for taking care of it.

Did you also upload the centos8 containers?  I could not find them.

**Comment by phracek** [comment]
Currently, there is no plan to move centos8 container into Quay.io too. Sorry.

**Comment by ibotty** [comment]
Are the centos8-Container kind-of unsupported in general?  They feel second-class with pretty much an sclorg-Repo.
