### ISSUE TITLE
Redis 6 base on RHEL-7/8

### ISSUE THREAD

**Issue by oleksandrsemak** [sclorg/redis-container#74]
Hello there,

Is it possible publish redis 6 base on RHEL 7/8 in Red Hat Container Catalog?

Thank you for advance.

**Comment by yrro** [comment]
`rhel8/redis-6` and `rhel9-redis6` are now both in the catalog.

**Comment by phracek** [comment]
redis-6 is already part in catalog as well. Closing this issue.
