### ISSUE TITLE
Build fail with rhel8 and redis6

### ISSUE THREAD

**Issue by noid999** [sclorg/redis-container#77]
Hi,
we tring to build an redis6 Image with ubi8. The building system is a Centos7,  make build TARGET=centos7 VERSIONS=5 is working fine. We tried manual with Dockerfile.rhel8 under /root/redis-container/6 just for testing but its not working. Its like the repos are not there, we get the Error: Problems in request: missing groups or modules: redis:6. 
If we jump in the container the line yum -y module enable redis:$REDIS_VERSION ist not working. Do we need a subscirbed RedHat system to build redis6 on ubi8? What have we overlooked?
 

```
[root@sl8-3064 6]# docker build --no-cache -t redis:1 .
Sending build context to Docker daemon  48.64kB
Step 1/13 : FROM registry.access.redhat.com/ubi8/s2i-core
 ---> ca53053fa8ed
Step 2/13 : ENV REDIS_VERSION=6     HOME=/var/lib/redis
 ---> Running in 15bb10a9378c
Removing intermediate container 15bb10a9378c
 ---> 922ed1790585
Step 3/13 : ENV SUMMARY="Redis in-memory data structure store, used as database, cache and message broker"     DESCRIPTION="Redis $REDIS_VERSION available as container, is an advanced key-value store. It is often referred to as a data structure server since keys can contain strings, hashes, lists, sets and sorted sets. You can run atomic operations on these types, like appending to a string; incrementing the value in a hash; pushing to a list; computing set intersection, union and difference; or getting the member with highest ranking in a sorted set. In order to achieve its outstanding performance, Redis works with an in-memory dataset. Depending on your use case, you can persist it either by dumping the dataset to disk every once in a while, or by appending each command to a log."
 ---> Running in b3d0b429195e
Removing intermediate container b3d0b429195e
 ---> e829f7228165
Step 4/13 : LABEL summary="$SUMMARY"       description="$DESCRIPTION"       io.k8s.description="$DESCRIPTION"       io.k8s.display-name="Redis $REDIS_VERSION"       io.openshift.expose-services="6379:redis"       io.openshift.tags="database,redis,redis$REDIS_VERSION,redis-$REDIS_VERSION"       com.redhat.component="redis-$REDIS_VERSION-container"       name="rhel8/redis-$REDIS_VERSION"       version="1"       com.redhat.license_terms="https://www.redhat.com/en/about/red-hat-end-user-license-agreements#rhel"       usage="podman run -d --name redis_database -p 6379:6379 rhel8/redis-$REDIS_VERSION"       maintainer="SoftwareCollections.org <sclorg@redhat.com>"
 ---> Running in 84646eb28e1e
Removing intermediate container 84646eb28e1e
 ---> 79df1a40f241
Step 5/13 : EXPOSE 6379
 ---> Running in 62cccedd138f
Removing intermediate container 62cccedd138f
 ---> 8a62316bb4a9
Step 6/13 : RUN getent group  redis &> /dev/null || groupadd -r redis &> /dev/null &&     usermod -l redis -aG redis -c 'Redis Server' default &> /dev/null &&     yum -y module enable redis:$REDIS_VERSION &&     INSTALL_PKGS="policycoreutils redis" &&     yum install -y --setopt=tsflags=nodocs $INSTALL_PKGS &&     rpm -V $INSTALL_PKGS &&     yum -y clean all --enablerepo='*' &&     mkdir -p /var/lib/redis/data && chown -R redis.0 /var/lib/redis &&     [[ "$(id redis)" == "uid=1001(redis)"* ]]
 ---> Running in 938b54e79adf
Updating Subscription Management repositories.
Unable to read consumer identity

This system is not registered to Red Hat Subscription Management. You can use subscription-manager to register.

Red Hat Universal Base Image 8 (RPMs) - BaseOS  6.3 MB/s | 777 kB     00:00
Red Hat Universal Base Image 8 (RPMs) - AppStre  14 MB/s | 5.2 MB     00:00
Red Hat Universal Base Image 8 (RPMs) - CodeRea 183 kB/s |  15 kB     00:00
Error: Problems in request:
missing groups or modules: redis:6
The command '/bin/sh -c getent group  redis &> /dev/null || groupadd -r redis &> /dev/null &&     usermod -l redis -aG redis -c 'Redis Server' default &> /dev/null &&     yum -y module enable redis:$REDIS_VERSION &&     INSTALL_PKGS="policycoreutils redis" &&     yum install -y --setopt=tsflags=nodocs $INSTALL_PKGS &&     rpm -V $INSTALL_PKGS &&     yum -y clean all --enablerepo='*' &&     mkdir -p /var/lib/redis/data && chown -R redis.0 /var/lib/redis &&     [[ "$(id redis)" == "uid=1001(redis)"* ]]' returned a non-zero code: 1

```

**Comment by phracek** [comment]
The failure is expected. You need to have access to RHEL-8 repositories or you need to be subscribed.

**Comment by noid999** [comment]
Hi @phracek,

thanks for your Help.

I have looked the last few nights what else it can be except the licenses. I noticed that there is no module redis:6. There seems to be the error. 

The latest module that Redhat gives in combination with ubi8/RHEL8 is redis:5. I have done a $ "yum module" list on registered RHEL 8 machines and there is just redis:5. 

Even if you look on the official site there is only redis:5
Source: [RedHat](https://access.redhat.com/support/policy/updates/rhel8-app-streams-life-cycle?extIdCarryOver=true&sc_cid=701f2000001Css5AAC)

Finally redis:6 is announced with Redhat 8.4. Then the Dockerfile should work on a registered RHEL 8.4 system. [Link](https://www.phoronix.com/scan.php?page=news_item&px=RHEL-8.4-Beta-Released)

In my opinion the Dockerfile could never work or has anyone managed to build a ubi8/redis6 image with it?

I will try to install and test on a VM with RHEL 8.4 in the near future and tell if it worked

**Comment by phracek** [comment]
@noid999 Redis-6 image is not ubi-8 based image. Redis-6 is not part of the Red Hat Universal Base Image eco-system. See https://catalog.redhat.com/software/search?type=Containerized%20application

For more information please see https://access.redhat.com/documentation/en-us/red_hat_enterprise_linux/9/html/building_running_and_managing_containers/assembly_adding-software-to-a-ubi-container_building-running-and-managing-containers#con_adding-software-to-a-ubi-container-on-a-subscribed-host_assembly_adding-software-to-a-ubi-container.

Your host system has to be subscribed to RHEL.

**Comment by phracek** [comment]
@noid999 This issue is not relevant to redis-container, but subscribed host. Closing this issue. Feel free to re-open it.
