### ISSUE TITLE
How do we enable TLS for this Redis 6 container

### ISSUE THREAD

**Issue by deekshahegde86** [sclorg/redis-container#80]
How do we enable TLS for this Redis 6 container. Dont see an option to provide config file.

**Comment by deekshahegde86** [comment]
Hello @phracek  can you please help with this issue.

**Comment by phracek** [comment]
@deekshahegde86 I have browsed the container sources and I don't think TLS is supported at all. I have found a documentation like this https://redis.io/topics/encryption where is mentioned how to configure redis to support TLS?

Do you want to use redis container by docker engine or in OpenShift?

**Comment by phracek** [comment]
Closing this issue, because in OpenShift environment it does not make sense to implement TLS support. Do you have any use case for it? Feel free to re-open this issue. Or even file a PR. 

Nowadays we do not have the capacity to implement new features.
